name: Steam AppIDs

on:
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

jobs:
  fetch:
    name: Fetch
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: '3.12'
          check-latest: true
          architecture: x64
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          mkdir assets/
      - name: Fetch Steam AppIDs for games
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
        run: |
          python3 -m steam_appids
          mv steam_appids.json assets/
      - uses: actions/upload-pages-artifact@v3
        id: deployment
        with:
          path: assets/

  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: fetch
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
